[package]
name = "mongodb-arrow-connector"
version = "0.1.0"
authors = ["Neville Dipale <nevilledips@gmail.com>"]
edition = "2018"

[dependencies]
bson = "0.14"
mongodb = "0.9.2"
arrow = "0.16.0"
chrono = "0.4"