[package]
name = "mongodb-arrow-connector"
description = "MongoDB connector that reads and writes data to/from Apache Arrow"
version = "0.2.0"
authors = ["Neville Dipale <nevilledips@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["apache-arrow", "mongodb"]
categories = ["database"]
readme = "README.md"
repository = "https://github.com/TheDataEngine/mongodb-arrow-connector/ "

[dependencies]
bson = "1.0"
mongodb = { version = "1.0", default-features = false, features = ["sync"] }
arrow = { version = "4.0", default-features = false }
chrono = "0.4"