[package]
name = "mongodb-arrow-connector"
description = "MongoDB connector that reads and writes data to/from Apache Arrow"
version = "0.1.0"
authors = ["Neville Dipale <nevilledips@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["apache-arrow", "mongodb"]
categories = ["database"]
readme = "README.md"
repository = "https://github.com/TheDataEngine/mongodb-arrow-connector/ "

[dependencies]
bson = "0.14"
mongodb = "0.9.2"
arrow = "0.16.0"
chrono = "0.4"